kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dailyvolume-pvc-01
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fb-nfs3
  resources:
    requests:
      storage: 10Gi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: esrally-dailyvolume
spec:
  #completions: 1
  #parallelism: 1
  template:
    spec:
      containers:
      - name: esrally
        image: elastic/rally:2.3.1
        env:
        - name: ELASTICPASS
          valueFrom:
            secretKeyRef:
              name: ssdemo-es-elastic-user
              key: elastic
        args: ['race',
               '--pipeline=benchmark-only',
               '--track=eventdata',
               '--track-repository=eventdata',
               '--challenge=index-logs-fixed-daily-volume',
               '--target-hosts=http://elastic:8P6p56n43GdhT0tStwh6n7e8@ssdemo-es-http.default:9200',
               '--client-options=timeout:60,use_ssl:false,verify_certs:false,basic_auth_user:''elastic''',
               '--track-params=/rally_param/params.json']
        resources:
            requests:
              memory: 52Gi
              cpu: 6500m
        volumeMounts:
        - name: trackparams-cfg-vol
          mountPath: /rally_param
        - name: esrally-data
          mountPath: /rally/.rally
        - name: rally-ini
          mountPath: /rally/.rally/rally.ini
          subPath: rally.ini
      restartPolicy: Never
      volumes:
        - name: trackparams-cfg-vol
          configMap:
            name: dailyvolume-trackparams-cfg-01
        - name: rally-ini
          configMap:
            name: dailyvolume-esrally-ini
        - name: esrally-data
          persistentVolumeClaim:
            claimName: dailyvolume-pvc-01

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dailyvolume-trackparams-cfg-01
data:
  params.json: |
    {
      "number_of_shards": 4,
      "number_of_replicas": 1,
      "bulk_indexing_clients": 4,
      "daily_logging_volume": "1GB",
      "bulk_size": 10000,
      "starting_point": "2023-02-01:00:00:00",
      "number_of_days": 1
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dailyvolume-esrally-ini
data:
  rally.ini: |
    [meta]
    config.version = 17
    
    [system]
    env.name = local
    
    [node]
    root.dir = /rally/.rally/benchmarks
    src.root.dir = /rally/.rally/benchmarks/src
    
    [source]
    remote.repo.url = https://github.com/elastic/elasticsearch.git
    elasticsearch.src.subdir = elasticsearch
    
    [benchmarks]
    local.dataset.cache = /rally/.rally/benchmarks/data
    
    [reporting]
    datastore.type = elasticsearch
    datastore.host = ssdemo-es-http.default
    datastore.port = 9200
    datastore.secure = false
    datastore.ssl.verification_mode = none
    datastore.user = elastic
    datastore.password = 8P6p56n43GdhT0tStwh6n7e8
    
    
    [tracks]
    default.url = https://github.com/elastic/rally-tracks
    eventdata.url = https://github.com/elastic/rally-eventdata-track
    
    [teams]
    default.url = https://github.com/elastic/rally-teams
    
    [defaults]
    preserve_benchmark_candidate = false
    
    [distributions]
    release.cache = true
