apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: reddot
spec:
  version: 7.6.0
  nodeSets:
  - name: default
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
    volumeClaimTemplates:
    - metadata:
        name: elastic-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        storageClassName: pure-file


---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: reddot
spec:
  version: 7.6.0
  count: 1
  elasticsearchRef:
    name: reddot
