apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: reddot
  namespace: elastic
spec:
  version: 7.12.1
  nodeSets:
  - name: master
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: true
      thread_pool.snapshot.max: 4
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: pure-file
    podTemplate:
      spec:
        initContainers:
          - name: install-plugins
            command:
              - sh
              - -c
              - |
                bin/elasticsearch-plugin remove --batch repository-s3
                bin/elasticsearch-plugin install --batch repository-s3
          - name: add-access-keys
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: es-s3-keys
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: es-s3-keys
                  key: secret-key
            command:
              - sh
              - -c
              - |
                echo $AWS_ACCESS_KEY_ID | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
                echo $AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          resources:
            requests:
              memory: 6Gi
              cpu: 1
  - name: data
    count: 2
    config:
      node.master: false
      node.data: true
      node.ingest: true
      thread_pool.snapshot.max: 4
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: pure-file
    podTemplate:
      spec:
        initContainers:
          - name: install-plugins
            command:
              - sh
              - -c
              - |
                bin/elasticsearch-plugin remove --batch repository-s3
                bin/elasticsearch-plugin install --batch repository-s3
          - name: add-access-keys
            env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: es-s3-keys
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: es-s3-keys
                  key: secret-key
            command:
              - sh
              - -c
              - |
                echo $AWS_ACCESS_KEY_ID | bin/elasticsearch-keystore add --stdin --force s3.client.default.access_key
                echo $AWS_SECRET_ACCESS_KEY | bin/elasticsearch-keystore add --stdin --force s3.client.default.secret_key
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms4g -Xmx4g
          resources:
            requests:
              memory: 6Gi
              cpu: 1

---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: reddot
  namespace: elastic
spec:
  version: 7.12.1
  count: 1
  elasticsearchRef:
    name: reddot
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 2Gi
            cpu: 1


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: elastic
  annotations:
    haproxy.org/ssl-passthrough: "true"
spec:
  rules:
  - host: kibana.purestorage.int
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: reddot-kb-http
            port:
              number: 5601

